services:
  servletwebapp2:
    build: .
    image: servletwebapp2
    container_name: servletwebapp2
    ports:
      - 8081:8081
    networks:
      - webapp-net

  webap-db:
    image: postgres:16.1
    container_name: webap-db
    ports:
      - 5432:5432
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=1331
      - JDBC_DEFAULT_SCHEMA=servlets
      - JDBC_USERS_TABLE=users
      - JDBC_PROJECTS_TABLE=projects
      - JDBC_PROJECT_USERS_TABLE=project_users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 5
    networks:
      - webapp-net

networks:
  webapp-net:
    driver: bridge
