# Используем официальный образ GlassFish 7 с JDK 17
FROM eclipse/glassfish:7.0-jdk17
# Установка рабочей директории (опционально)
WORKDIR /opt/glassfish7

# Добавляем драйвер PostgreSQL в GlassFish
# Путь для JDBC-драйверов в GlassFish: /opt/glassfish7/glassfish/lib/
ADD https://jdbc.postgresql.org/download/postgresql-42.6.0.jar /opt/glassfish7/glassfish/lib/postgresql.jar

# Копируем WAR-файл в папку авто-деплоя GlassFish
# Приложение будет доступно по корневому пути (http://localhost:8080/)
COPY target/ServletWebApp2.war /opt/glassfish7/glassfish/domains/domain1/autodeploy/ROOT.war

# Настройка переменных среды (опционально)
ENV JDK_JAVA_OPTIONS=""
ENV POSTGRES_JDBC_URL="jdbc:postgresql://webap-db:5432/postgres"
ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="1331"

# Открываем порты:
# - 8080 для HTTP
# - 4848 для админ-консоли
EXPOSE 8080 4848

# Команда запуска GlassFish (уже предустановлена в базовом образе)
# CMD ["asadmin", "start-domain", "--verbose", "domain1"]